name: PatricioBuenrostroFanClub
favicon: null
layout_spectrum: 0
typography_spectrum: 0.58446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#22244b'
    - '#c99d9a'
    - '#63444c'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.24496516515500844
  saturation: 0.35665494995191693
  rhythmicContrast: 0.01821472030133009
purpose: []
