name: PatricioBuenrostroFanClub
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60975
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Patricio Buenrostro Fan Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1c11'
    - '#0077aa'
    - '#ffb570'
    - '#902210'
    - '#ff5533'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
